#!/usr/bin/env python3
"""
Test Scalping Model - Manual test for the scalping signal generation.

This script tests the scalping model integration without executing trades.
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# Add backend to path
backend_dir = Path(__file__).parent.parent
sys.path.insert(0, str(backend_dir))

from app.core.database import SessionLocal
from app.models.ml import MLModel
from app.services.prediction_service import PredictionService
from app.services.market_data import MarketDataFetcher


def test_scalping_model():
    """Test the scalping model prediction."""
    
    print("=" * 60)
    print("🧪 TESTING SCALPING MODEL INTEGRATION")
    print("=" * 60)
    print(f"   Time: {datetime.now().isoformat()}")
    
    db = SessionLocal()
    
    try:
        # Get active scalping model
        model = db.query(MLModel).filter(
            MLModel.is_active == True,
            MLModel.symbol == "XAUUSD"
        ).first()
        
        if not model:
            print("❌ No active XAUUSD model found!")
            return False
        
        print(f"\n📊 Model: {model.name}")
        print(f"   Type: {model.model_type}")
        print(f"   Timeframe: {model.timeframe}")
        print(f"   File: {model.file_path}")
        
        # Check model file
        if not os.path.exists(model.file_path):
            print(f"❌ Model file not found: {model.file_path}")
            return False
        
        print(f"   ✅ File exists")
        
        # Get model config
        config = model.config or {}
        print(f"\n⚙️  Configuration:")
        print(f"   Strategy Type: {config.get('strategy_type', 'unknown')}")
        print(f"   Confidence Threshold: {config.get('confidence_threshold', 0.55):.0%}")
        print(f"   TP: {config.get('tp_pips', 5.0)} pips")
        print(f"   SL: {config.get('sl_pips', 8.0)} pips")
        
        # Fetch market data
        print(f"\n📈 Fetching XAUUSD M15 data...")
        market_data = MarketDataFetcher.fetch_data("XAUUSD", "M15", bars=200)
        
        if market_data is None or len(market_data) < 50:
            print("❌ Could not fetch sufficient market data")
            return False
        
        print(f"   Fetched {len(market_data)} bars")
        print(f"   Latest close: ${market_data['close'].iloc[-1]:.2f}")
        print(f"   Latest time: {market_data.index[-1] if hasattr(market_data.index[-1], 'strftime') else 'N/A'}")
        
        # Generate prediction
        print(f"\n🎯 Generating prediction...")
        prediction_service = PredictionService(db)
        
        result = prediction_service.generate_prediction(
            model=model,
            symbol="XAUUSD",
            use_strategy_rules=False,
            save_to_db=False
        )
        
        print(f"\n📊 PREDICTION RESULT:")
        print("-" * 40)
        print(f"   Direction:    {result.direction}")
        print(f"   Confidence:   {result.confidence:.2%}")
        print(f"   ML Signal:    {result.ml_signal}")
        print(f"   Entry Price:  ${result.entry_price:.2f}")
        print(f"   Stop Loss:    {f'${result.stop_loss:.2f}' if result.stop_loss else 'N/A'}")
        print(f"   Take Profit:  {f'${result.take_profit:.2f}' if result.take_profit else 'N/A'}")
        print(f"   Should Trade: {result.should_trade}")
        print(f"   Generated By: {result.generated_by}")
        print("-" * 40)
        
        # Evaluate result
        if result.direction != "HOLD" and result.confidence >= config.get('confidence_threshold', 0.55):
            print(f"\n🚀 SIGNAL DETECTED!")
            print(f"   {result.direction} XAUUSD @ ${result.entry_price:.2f}")
            print(f"   TP: ${result.take_profit:.2f} (+{config.get('tp_pips', 5.0)} pips)")
            print(f"   SL: ${result.stop_loss:.2f} (-{config.get('sl_pips', 8.0)} pips)")
        else:
            reason = "low confidence" if result.confidence < config.get('confidence_threshold', 0.55) else "no signal"
            print(f"\n⏸️  NO TRADE: {reason}")
            print(f"   Confidence {result.confidence:.2%} vs threshold {config.get('confidence_threshold', 0.55):.0%}")
        
        print(f"\n✅ Test completed successfully!")
        return True
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return False
    finally:
        db.close()


def main():
    """Main entry point."""
    success = test_scalping_model()
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
