"""Telegram notification service for trading signals and alerts."""

import httpx
from typing import Optional, Dict, Any
from app.core.logging import get_logger

logger = get_logger(__name__)


class TelegramService:
    """Send notifications via Telegram Bot API."""
    
    BASE_URL = "https://api.telegram.org"
    
    def __init__(self, bot_token: str, chat_id: str):
        """
        Initialize Telegram service.
        
        Args:
            bot_token: Telegram Bot API token (from @BotFather)
            chat_id: Chat/Group ID to send messages to
        """
        self.bot_token = bot_token
        self.chat_id = chat_id
        self.api_url = f"{self.BASE_URL}/bot{bot_token}"
    
    async def send_message(
        self, 
        text: str, 
        parse_mode: str = "HTML",
        disable_notification: bool = False
    ) -> bool:
        """
        Send a text message to the configured chat.
        
        Args:
            text: Message text (supports HTML formatting)
            parse_mode: "HTML" or "Markdown"
            disable_notification: If True, send silently
            
        Returns:
            True if message was sent successfully
        """
        if not self.bot_token or not self.chat_id:
            logger.warning("Telegram not configured (missing bot_token or chat_id)")
            return False
        
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(
                    f"{self.api_url}/sendMessage",
                    json={
                        "chat_id": self.chat_id,
                        "text": text,
                        "parse_mode": parse_mode,
                        "disable_notification": disable_notification,
                    }
                )
                
                if response.status_code == 200:
                    logger.info(f"Telegram message sent to {self.chat_id}")
                    return True
                else:
                    error = response.json()
                    logger.error(f"Telegram API error: {error}")
                    return False
                    
        except Exception as e:
            logger.error(f"Failed to send Telegram message: {e}")
            return False
    
    async def test_connection(self) -> Dict[str, Any]:
        """
        Test the Telegram bot connection.
        
        Returns:
            Dict with success status and bot info
        """
        if not self.bot_token:
            return {"success": False, "error": "Bot token not configured"}
        
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                # Get bot info
                response = await client.get(f"{self.api_url}/getMe")
                
                if response.status_code == 200:
                    data = response.json()
                    if data.get("ok"):
                        bot_info = data.get("result", {})
                        
                        # Try sending a test message
                        test_result = await self.send_message(
                            "🤖 <b>NusaTrade Bot Connected!</b>\n\n"
                            "You will receive trading signals here.\n"
                            "Manage notifications in Settings."
                        )
                        
                        return {
                            "success": True,
                            "bot_username": bot_info.get("username"),
                            "bot_name": bot_info.get("first_name"),
                            "test_message_sent": test_result,
                        }
                
                return {"success": False, "error": "Invalid bot token"}
                
        except Exception as e:
            return {"success": False, "error": str(e)}


def format_signal_message(signal_data: Dict[str, Any]) -> str:
    """
    Format a trading signal for Telegram.
    
    Args:
        signal_data: Signal information dict
        
    Returns:
        Formatted HTML message
    """
    direction = signal_data.get("direction", "UNKNOWN")
    symbol = signal_data.get("symbol", "N/A")
    confidence = signal_data.get("confidence", 0) * 100
    entry_price = signal_data.get("entry_price", 0)
    stop_loss = signal_data.get("stop_loss", 0)
    take_profit = signal_data.get("take_profit", 0)
    
    # Emoji based on direction
    emoji = "🟢" if direction == "BUY" else "🔴" if direction == "SELL" else "⚪"
    
    message = f"""
{emoji} <b>TRADING SIGNAL</b> {emoji}

<b>Symbol:</b> {symbol}
<b>Direction:</b> {direction}
<b>Confidence:</b> {confidence:.1f}%

<b>Entry:</b> {entry_price:.5f}
<b>Stop Loss:</b> {stop_loss:.5f}
<b>Take Profit:</b> {take_profit:.5f}

<i>Generated by NusaTrade ML Bot</i>
"""
    return message.strip()


def format_trade_executed_message(trade_data: Dict[str, Any]) -> str:
    """
    Format a trade execution notification for Telegram.
    
    Args:
        trade_data: Trade information dict
        
    Returns:
        Formatted HTML message
    """
    trade_type = trade_data.get("type", "UNKNOWN")
    symbol = trade_data.get("symbol", "N/A")
    lot_size = trade_data.get("lot_size", 0)
    entry_price = trade_data.get("entry_price", 0)
    stop_loss = trade_data.get("stop_loss", 0)
    take_profit = trade_data.get("take_profit", 0)
    ticket = trade_data.get("ticket", "N/A")
    
    emoji = "✅" if trade_type == "BUY" else "🔻"
    
    message = f"""
{emoji} <b>TRADE EXECUTED</b> {emoji}

<b>Symbol:</b> {symbol}
<b>Type:</b> {trade_type}
<b>Lot Size:</b> {lot_size}
<b>Entry Price:</b> {entry_price:.5f}

<b>SL:</b> {stop_loss:.5f}
<b>TP:</b> {take_profit:.5f}

<b>Ticket:</b> #{ticket}

<i>Auto-executed by NusaTrade</i>
"""
    return message.strip()


def format_trade_closed_message(trade_data: Dict[str, Any]) -> str:
    """
    Format a trade closed notification for Telegram.
    
    Args:
        trade_data: Trade information dict
        
    Returns:
        Formatted HTML message
    """
    symbol = trade_data.get("symbol", "N/A")
    profit = trade_data.get("profit", 0)
    pips = trade_data.get("pips", 0)
    close_price = trade_data.get("close_price", 0)
    ticket = trade_data.get("ticket", "N/A")
    
    emoji = "💰" if profit > 0 else "📉"
    status = "PROFIT" if profit > 0 else "LOSS"
    
    message = f"""
{emoji} <b>TRADE CLOSED</b> {emoji}

<b>Symbol:</b> {symbol}
<b>Result:</b> {status}
<b>P/L:</b> ${profit:.2f} ({pips:.1f} pips)
<b>Close Price:</b> {close_price:.5f}

<b>Ticket:</b> #{ticket}
"""
    return message.strip()


async def send_signal_notification(
    user_settings: Dict[str, Any],
    signal_data: Dict[str, Any],
) -> Dict[str, bool]:
    """
    Send signal notification to all configured channels.
    
    Args:
        user_settings: User's notification settings
        signal_data: Signal information
        
    Returns:
        Dict with results per channel
    """
    results = {
        "telegram": False,
        "email": False,
    }
    
    # Telegram notification
    if user_settings.get("telegramEnabled") and user_settings.get("telegramBotToken"):
        service = TelegramService(
            bot_token=user_settings.get("telegramBotToken", ""),
            chat_id=user_settings.get("telegramChatId", ""),
        )
        message = format_signal_message(signal_data)
        results["telegram"] = await service.send_message(message)
    
    # Email notification (handled separately in email_service)
    if user_settings.get("emailNotifications") and user_settings.get("tradeAlerts"):
        # TODO: Call email service here
        results["email"] = True  # Placeholder
    
    return results


async def send_trade_notification(
    user_settings: Dict[str, Any],
    trade_data: Dict[str, Any],
    action: str = "executed",  # "executed" or "closed"
) -> Dict[str, bool]:
    """
    Send trade notification to all configured channels.
    
    Args:
        user_settings: User's notification settings
        trade_data: Trade information
        action: "executed" or "closed"
        
    Returns:
        Dict with results per channel
    """
    results = {
        "telegram": False,
        "email": False,
    }
    
    # Telegram notification
    if user_settings.get("telegramEnabled") and user_settings.get("telegramBotToken"):
        service = TelegramService(
            bot_token=user_settings.get("telegramBotToken", ""),
            chat_id=user_settings.get("telegramChatId", ""),
        )
        
        if action == "executed":
            message = format_trade_executed_message(trade_data)
        else:
            message = format_trade_closed_message(trade_data)
            
        results["telegram"] = await service.send_message(message)
    
    return results
